services:
  app:
    image: ghcr.io/tigerowo/infinite-canvas:latest
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: always
    container_name: infinite-canvas
    network_mode: host
    entrypoint: ["/bin/sh", "/app/docker-entrypoint.sh"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./docker-entrypoint.sh:/app/docker-entrypoint.sh:ro
      - ./server:/app/server:ro
    restart: unless-stopped
